server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cyfyang/itoken-config.git    # GitHub上面的git仓库名字
          ### 搜索目录
          search-paths:
            - respo
      ### 读取分支
      label: master
      #rabbitmq相关配置
    bus:
      refresh:
        enabled: true
  rabbitmq:
    host: 192.168.73.99
    port: 5672
    username: rabbit
    password: 123456

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

